services:
  react_app:
    build: ./front-end
    image: react_app_image
    container_name: react_app
    volumes:
      - react_build:/var/www/html
  nginx:
    build: ./nginx
    image: nginx_image
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - react_build:/var/www/html
    depends_on:
      - react_app

volumes:
  react_build:
